spring.application.name=ALMXN
server.port=8085


# Configuración de H2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# Sincronización Scripts SQL y JPA
spring.jpa.defer-datasource-initialization=true

# Configuración de Spring Data JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Forzar la ejecución de tus scripts siempre al iniciar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Habilitar la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración del pool de conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# Codificación de caracteres (Evita problemas con la 'ñ' y acentos)
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Desactiva la caché en desarrollo para ver los cambios en el HTML sin reiniciar el servidor
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8